version: '3.1'
services:
  email-notifier:
    ports:
      - "4000:3000"
    build: ./email-notifier
    command: '/bin/sh -c "npm i -g nodemon && nodemon index.js"'
    volumes: 
      - ./email-notifier:/app
      - /app/node_modules
  subscriptions-api:
    build: ./subscriptions-api
    ports:
      - "4001:3000"
    command: '/bin/sh -c "npm i -g nodemon && nodemon index.js"'
    volumes: 
      - ./subscriptions-api:/app
      - /app/node_modules
  source-publisher:
    command: '/bin/sh -c "npm i -g nodemon && nodemon index.js"'
    build: ./source-publisher
    volumes: 
      - ./source-publisher:/app
      - /app/node_modules
  subscriptions-worker:
    command: '/bin/sh -c "npm i -g nodemon && nodemon index.js"'
    build: ./subscriptions-worker
    volumes: 
      - ./subscriptions-worker:/app
      - /app/node_modules
  mongo-express:
    image: mongo-express
    ports:
      - 4010:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example


  