version: '3.1'

services:
  email-notifier:
    image: yshayy/nodejs-meetup-email-notifier
    build: ./email-notifier
    environment:
      - SENDER_EMAIL=yshay@nodejs-docker.test
      - SENDGRID_API_KEY=***
