version: '3.1'

services:
  email-notifier:
    image: yshay/nodejs-meetup-email-notifier
    environment:
      - SENDER_EMAIL=yshay@nodejs-docker.test
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
  subscriptions-api:
    image: yshay/nodejs-meetup-subscriptions-api
    depends_on:
      - mongo
      - nats
    ports:
      - 9000:3000
    environment:
      - MONGO_URL=mongodb://root:example@mongo
      - NATS_URL=nats://nats:4222
  source-publisher:
    image: yshay/nodejs-meetup-source-publisher
    depends_on:
      - subscriptions-api
      - nats
    environment:
      - SUBSCRIPTIONS_API_URL=http://subscriptions-api:3000
      - NATS_URL=nats://nats:4222

  subscriptions-worker:
    image: yshay/nodejs-meetup-subscriptions-worker
    depends_on:
      - mongo
      - nats
      - email-notifier
    environment:
      - NATS_URL=nats://nats:4222
      - EMAIL_NOTIFIER_URL=http://email-notifier:3000
      - SUBSCRIPTIONS_API_URL=http://subscriptions-api:3000
  
  mongo:
    image: mongo
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nats:
    image: nats:1.3.0-linux
    logging:
      driver: none